# Generated by Django 6.0.2 on 2026-04-20 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_stripe_ids_to_charfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_bg', models.CharField(blank=True, max_length=255, null=True)),
                ('excerpt_en', models.TextField(blank=True, null=True)),
                ('excerpt_bg', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('content_en', models.JSONField(blank=True, default=dict)),
                ('content_bg', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
