# Generated by Codex on 2026-07-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В работа'), ('waiting_customer', 'Изчаква клиент'), ('resolved', 'Решена'), ('closed', 'Затворена')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Нисък'), ('normal', 'Нормален'), ('high', 'Висок'), ('urgent', 'Спешен')], default='normal', max_length=10)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to='api.order')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', '-id'],
                'verbose_name': 'следпродажбен казус',
                'verbose_name_plural': 'следпродажбено обслужване',
            },
        ),
    ]
